### PR TITLE
Improve README

### PR DESCRIPTION
**Pull request by danielpassos**

### CODE REVIEW

**Comment by edewit** [comment]
The google account setting do not work for iOS, but the other way around they do work. So if you choose Installed Application -> iOS and fill in you bundle id, these settings also work for android. That way we don't have to add anything specific in the javascript side of things.

**Comment by edewit** [comment]
How did you manage to open it in android studio? I get error importing the project, can't we just tell users to edit the build.gradle file and run gradle from the command line?

**Comment by danielpassos** [comment]
@edewit I've just import that using the `build.gradle`. 
1. Open an existent ...
2. Select build.gradle

**Comment by danielpassos** [comment]
@edewit Btw if edit the build.gradle and run command line works for you, go ahead.

**Comment by edewit** [comment]
If I import the gradle project it complains about the android gradle plugin being outdated, works fine on the command line. If we don't need specific platform IDE's I think it's better to not mention them. Also could not reproduce this missing activity you had, can you try and see that the command line works.

**Pull request merged**
